Repository SubZero-Robotics/2024-CommandRobot, pull requests merged in 2024-01, with the labels that each got.

#20 Skeletonize StateManager
  src/main/cpp/utils/State.h
  src/main/include/subsystems/WristSubsystem.h
  src/main/include/utils/State.h
  vendordeps/PathplannerLib.json
Labels: feature

#21 Support the newest features from the ConnectorX firmware
  src/main/cpp/moduledrivers/ConnectorX.cpp
  src/main/include/moduledrivers/ConnectorX.h
Labels: enhancement

#23 Fix Connector X
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/moduledrivers/ConnectorX.cpp
  src/main/cpp/subsystems/DriveSubsystem.cpp
  src/main/include/moduledrivers/ConnectorX.h
  src/main/include/subsystems/BaseSingleAxisSubsystem.h
  src/main/include/subsystems/WristSubsystem.h
  src/main/include/utils/ConsoleLogger.h
  src/main/include/utils/ILogger.h
  src/main/include/utils/ShuffleboardLogger.h
Labels: bug, enhancement

#22 Add preprocessor macros to check robot
  src/main/cpp/Robot.cpp
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/subsystems/DriveSubsystem.cpp
  src/main/cpp/utils/State.cpp
  src/main/include/Constants.h
Labels: enhancement

#24 Skeletonize climbing subsystem
  src/main/cpp/Robot.cpp
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/subsystems/ClimbSubsystem.cpp
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/subsystems/BaseSingleAxisSubsystem.h
  src/main/include/subsystems/ClimbSubsystem.h
  src/main/include/subsystems/LeftClimbSubsystem.h
  src/main/include/subsystems/RightClimbSubsystem.h
  src/main/include/subsystems/WristSubsystem.h
Labels: feature

#26 Intake Subsystem Skeleton
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/subsystems/IntakeSubsystem.cpp
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/commands/IntakeInCommand.h
  src/main/include/commands/RotateWristCommand.h
  src/main/include/subsystems/IntakeSubsystem.h
  src/main/include/subsystems/WristSubsystem.h
Labels: feature, intake subsystem

#27 Scoring Subsystem
  src/main/cpp/subsystems/ScoringSubsystem.cpp
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/subsystems/IntakeSubsystem.h
  src/main/include/subsystems/ScoringSubsystem.h
Labels: feature, Scoring subsystem

#34 Connector-X Zones
  src/main/cpp/moduledrivers/ConnectorX.cpp
  src/main/include/commands/Funni.h
  src/main/include/moduledrivers/ConnectorX.h
Labels: enhancement

#35 Create new multizone patterns
  src/main/cpp/subsystems/LedSubsystem.cpp
  src/main/include/moduledrivers/ConnectorX.h
  src/main/include/subsystems/LedSubsystem.h
Labels: enhancement

#37 Extend, Balance, and Retract commands
  build.gradle
  src/main/cpp/RobotContainer.cpp
  src/main/include/Constants.h
  src/main/include/commands/BalanceCommand.h
  src/main/include/commands/ExtendClimbCommand.h
  src/main/include/commands/RetractClimbCommand.h
  src/main/include/subsystems/BaseSingleAxisSubsystem.h
  src/main/include/subsystems/ClimbSubsystem.h
  src/main/include/subsystems/DriveSubsystem.h
Labels: feature, enhancement, climber subsystem, controls

#31 Add amp and speaker scoring commands :flushed:
  src/main/cpp/RobotContainer.cpp
  src/main/include/commands/IntakeInCommand.h
  src/main/include/commands/ScoreAmpCommand.h
  src/main/include/commands/ScoreSpeakerCommand.h
Labels: enhancement, Scoring subsystem

#39 Create base README
  README.md
  robot.png
Labels: documentation, enhancement

#38 Change controller bindings to command style, make score commands better
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/subsystems/IntakeSubsystem.cpp
  src/main/cpp/subsystems/ScoringSubsystem.cpp
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/commands/BaseScoreCommand.h
  src/main/include/commands/ScoreAmpCommand.h
  src/main/include/commands/ScoreSpeakerCommand.h
  src/main/include/commands/ScoreSubwooferCommand.h
  src/main/include/subsystems/IntakeSubsystem.h
  src/main/include/subsystems/ScoringSubsystem.h
Labels: enhancement, Scoring subsystem, controls

#42 General Cleanup, add drivetrain logging
  src/main/cpp/Robot.cpp
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/moduledrivers/ConnectorX.cpp
  src/main/cpp/subsystems/ClimbSubsystem.cpp
  src/main/cpp/subsystems/DriveSubsystem.cpp
  src/main/cpp/subsystems/IntakeSubsystem.cpp
  src/main/cpp/subsystems/LedSubsystem.cpp
  src/main/cpp/subsystems/ScoringSubsystem.cpp
  src/main/cpp/utils/ConsoleLogger.cpp
  src/main/cpp/utils/ShuffleboardLogger.cpp
  src/main/cpp/utils/State.cpp
  src/main/include/ColorConstants.h
  src/main/include/Constants.h
  src/main/include/RobotContainer.h
  src/main/include/commands/BalanceCommand.h
  src/main/include/commands/BaseScoreCommand.h
  src/main/include/commands/ExtendClimbCommand.h
  src/main/include/commands/Funni.h
  src/main/include/commands/IntakeInCommand.h
  src/main/include/commands/IntakeOutCommand.h
  src/main/include/commands/RetractClimbCommand.h
  src/main/include/moduledrivers/ConnectorX.h
  src/main/include/subsystems/BaseSingleAxisSubsystem.h
  src/main/include/subsystems/ClimbSubsystem.h
  src/main/include/subsystems/DriveSubsystem.h
  src/main/include/subsystems/ISingleAxisSubsystem.h
  src/main/include/subsystems/IntakeSubsystem.h
  src/main/include/subsystems/LedSubsystem.h
  src/main/include/subsystems/LeftClimbSubsystem.h
  src/main/include/subsystems/MAXSwerveModule.h
  src/main/include/subsystems/RightClimbSubsystem.h
  src/main/include/subsystems/ScoringSubsystem.h
  src/main/include/utils/ILogger.h
  src/main/include/utils/ShuffleboardLogger.h
  src/main/include/utils/State.h
Labels: enhancement

#45 Create auto paths
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/moduledrivers/ConnectorX.cpp
  src/main/deploy/pathplanner/autos/2 Note Auto.auto
  src/main/deploy/pathplanner/autos/2 Note Starting Away From Speaker.auto
  src/main/deploy/pathplanner/autos/4 Note Auto.auto
  src/main/deploy/pathplanner/autos/5 Note Auto.auto
  src/main/deploy/pathplanner/paths/Amp to Center Note 1.path
  src/main/deploy/pathplanner/paths/Amp to Center Note 2.path
  src/main/deploy/pathplanner/paths/Amp to Note 1.path
  src/main/deploy/pathplanner/paths/Amp to Note 2.path
  src/main/deploy/pathplanner/paths/Amp to Note 3.path
  src/main/deploy/pathplanner/paths/Amp to Podium.path
  src/main/deploy/pathplanner/paths/Center Field to Center Stage.path
  src/main/deploy/pathplanner/paths/Center Note 1 to Amp.path
  src/main/deploy/pathplanner/paths/Center Note 1 to Speaker.path
  src/main/deploy/pathplanner/paths/Center Note 2 to Amp.path
  src/main/deploy/pathplanner/paths/Center Note 2 to Speaker.path
  src/main/deploy/pathplanner/paths/Note 1 to Amp.path
  src/main/deploy/pathplanner/paths/Note 1 to Speaker.path
  src/main/deploy/pathplanner/paths/Note 2 to Amp.path
  src/main/deploy/pathplanner/paths/Note 2 to Speaker.path
  src/main/deploy/pathplanner/paths/Note 3 to Amp.path
  src/main/deploy/pathplanner/paths/Note 3 to Speaker.path
  src/main/deploy/pathplanner/paths/Podium to Amp.path
  src/main/deploy/pathplanner/paths/Speaker to Center Note 1.path
  src/main/deploy/pathplanner/paths/Speaker to Center Note 2.path
  src/main/deploy/pathplanner/paths/Speaker to Note 1.path
  src/main/deploy/pathplanner/paths/Speaker to Note 2.path
  src/main/deploy/pathplanner/paths/Speaker to Note 3.path
  src/main/deploy/pathplanner/paths/Start to Speaker.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Amp.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Podium.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Source 1.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Source 2.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Source 3.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Speaker.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Stage Left.path
  src/main/deploy/pathplanner/paths/Wing Line 1 to Wing Line 2.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Amp.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Podium.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Source 1.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Source 2.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Source 3.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Speaker.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Stage Right.path
  src/main/deploy/pathplanner/paths/Wing Line 2 to Wing Line 1.path
Labels: feature, drive subsystem

#44 State Management
  .vscode/settings.json
  src/main/cpp/Robot.cpp
  src/main/cpp/RobotContainer.cpp
  src/main/cpp/subsystems/DriveSubsystem.cpp
  src/main/cpp/subsystems/LedSubsystem.cpp
  src/main/cpp/subsystems/StateSubsystem.cpp
  src/main/cpp/utils/State.cpp
  src/main/deploy/pathplanner/paths/Note 2 to Podium.path
  src/main/include/Constants.h
  src/main/include/Robot.h
  src/main/include/RobotContainer.h
  src/main/include/autos/OnTheFlyFactory.h
  src/main/include/autos/PathFactory.h
  src/main/include/commands/BalanceCommand.h
  src/main/include/commands/BaseScoreCommand.h
  src/main/include/commands/DriveVelocityCommand.h
  src/main/include/commands/ExtendAbsoluteCommand.h
  src/main/include/subsystems/LedSubsystem.h
  src/main/include/subsystems/StateSubsystem.h
  src/main/include/utils/ConsoleLogger.h
  src/main/include/utils/ILogger.h
  src/main/include/utils/State.h
  src/test/cpp/main.cpp
Labels: enhancement, controls

#46 Add timeouts to auto command compositions
  src/main/cpp/subsystems/StateSubsystem.cpp
Labels: bug

#47 fix ifdef
  src/main/cpp/RobotContainer.cpp
  src/main/include/Constants.h
Labels: bug, drive subsystem

#49 Create actual autos that can be used in competition
  src/main/deploy/pathplanner/autos/2 in Amp.auto
  src/main/deploy/pathplanner/autos/2 in Speaker 2 in Amp.auto
  src/main/deploy/pathplanner/autos/3 in Amp.auto
  src/main/deploy/pathplanner/autos/3 in Speaker.auto
  src/main/deploy/pathplanner/paths/Amp to Note 1.path
  src/main/deploy/pathplanner/paths/Note 1 to Speaker.path
  src/main/deploy/pathplanner/paths/Note 3 to Speaker.path
  src/main/deploy/pathplanner/paths/Speaker to Note 1.path
  src/main/deploy/pathplanner/paths/Speaker to Note 2.path
  src/main/deploy/pathplanner/paths/Speaker to Note 3.path
Labels: enhancement, drive subsystem
